proxies:
  provider: proxyrack
  api_key: ""
  country: "US"

discord:
  bot_token: ""
  channel_id: "1307613131626905712"

telegram:
  bot_token: ""
  chat_id: ""

selenium:
  # Hypothesis testing:
  # - headless: false  -> closer to devtools/browser behavior
  # - disable_automation_flags: true -> reduce easy webdriver fingerprinting
  headless: false
  disable_automation_flags: true
  user_agent: ""

urls:
  - "https://www.americanexpress.com/en-us/referral/business/business-platinum-charge-card?CORID=H~A~N~S~I~M~N~w~h~k-1774524294632-787337&GENCODE=349993354373629&extlink=US-MGM-RAB-USEFULINKSL-copypaste-92-201279-K7I6%3A9948&ref=HANSIMNwhk&v=2&xl=cp10lg"

targets:
  - 300000
  - 200000

